### ISSUE TITLE
How can I make the tags not draggable?

### ISSUE THREAD

**Issue by mheiber** [prakhar1989/react-tags#56]
Is there a way to make the tags *not* draggable? I'm looking to do something like:

```javascript
<ReactTags draggable={false} ...>
```

Great library, thank you for sharing your work!

**Comment by ypling** [comment]
@prakhar1989  I know give a empty function to handleDrag can disable the drag behavior. Do you think its a good idea that check if props.handleDrag not a function set the draggable attribute to false?
I think disable the dragging animation is what people are looking for.

**Comment by prakhar1989** [comment]
>  check if props.handleDrag not a function set the draggable attribute to false

Yup, sounds good. Do you mind sending in a PR with this fix? :grinning:

**Comment by rnicholus** [comment]
Sounds like this was resolved in #58, so I'm going to close. Please let me know if I am mistaken.

**Comment by sw-yx** [comment]
note to others - can also disable the cursor change:

```css

/* Styles for selected tags */
div.ReactTags__selected span.ReactTags__tag {
    border: 1px solid #ddd;
    background: #eee;
    font-size: 12px;
    display: inline-block;
    padding: 5px;
    margin: 0 5px;
    /*cursor: move;*/
    border-radius: 2px;
}
```
